### ISSUE TITLE
Annotation error for hg19 based run

### ISSUE THREAD

**Issue by drumair** [cougarlj/COMPSRA#10]
Hi I am getting the following error for hg19 based run, though hg38 based run works smoothly

DEBUG   2020-12-17 13:58:33     BlockCompressedOutputStream     Using deflater: Deflater
13:58:33.605 [pool-4-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - edu.harvard.channing.compass.entity.DBTree; local class incompatible: stream classdesc serialVersionUID = 1208565614191564338, local class serialVersionUID = 556476181312992002
13:58:33.605 [pool-4-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Fail to find the prebuilt database obj file!
13:58:33.606 [pool-4-thread-1] WARN  edu.harvard.channing.compass.db.DB_miRBase - The prebuilt database file /home/COMPSRA/bundle_v1/prebuilt_db/miRBase_hg19.obj doesn't exist!
13:58:33.606 [pool-4-thread-1] INFO  edu.harvard.channing.compass.db.DB_miRBase - Try to build the database from local files /home/COMPSRA/bundle_v1/db/miRBase/miRBase_hg19.gff3 !
13:58:33.606 [pool-4-thread-1] INFO  edu.harvard.channing.compass.utility.ReadFile - Read File Error: Fail to read file: /home/COMPSRA/bundle_v1/db/miRBase/miRBase_hg19.gff3.
13:58:33.606 [pool-4-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - null
java.lang.NullPointerException
        at edu.harvard.channing.compass.utility.ReadFile.readGFF3(ReadFile.java:384)
        at edu.harvard.channing.compass.db.DB_miRBase.getForest(DB_miRBase.java:85)
        at edu.harvard.channing.compass.core.ann.IPTR_miRNA.buildForest(IPTR_miRNA.java:51)
        at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:78)
        at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:159)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
13:58:33.607 [main] ERROR edu.harvard.channing.compass.core.ann.Annotation - java.lang.NullPointerException
13:58:33.607 [main] INFO  edu.harvard.channing.compass.core.Produce - Error: Annotation module fails!

**Comment by cougarlj** [comment]
It's the version problem that the prebuilt database version is not fit for COMPSRA version. We haven't update hg19 for a long time, because few people used hg19. Let me build miRBase_hg19.obj for you. 
[miRBase_hg19.zip](https://github.com/cougarlj/COMPSRA/files/5718547/miRBase_hg19.zip)


Some users response that there is a bug in building STAR genome index. So please download the reference genome and build it by yourself. I can provide some commands as reference. 

wget http://hgdownload.cse.ucsc.edu/goldenPath/hg19/bigZips/hg19.fa.gz
gunzip hg19.fa.gz
/your/own/path/bundle_v1/plug/star/STAR-2.5.3a/bin/Linux_x86_64/STAR --runMode genomeGenerate --runThreadN 4  --genomeDir /your/own/path/bundle_v1/db/star/hg19 --genomeFastaFiles /your/own/path/bundle_v1/db/star/hg19/hg19.fa

If you have built this index by yourself, please delete the parameter "-mbi" in the command line. 

Best Wishes,
  Jiang Li

**Comment by drumair** [comment]
It still gives the same error

**Comment by cougarlj** [comment]
Dear drumair,

Can you download and try the latest COMPSRA that I have updated to GitHub
today?

Best Regards,
  Jiang LI
