### ISSUE TITLE
Custom STAR indices

### ISSUE THREAD

**Issue by riccardo-aiese** [cougarlj/COMPSRA#22]
Hello,
I would like to try COMPSRA with some smallRNA-seq datasets I have from human samples. Since I already have STAR installed and a genome index generated, I was wondering if I can provide the STAR execution path and the index path to COMPSRA instead of installing them. Is this possible?

Thank you
Riccardo

**Comment by cougarlj** [comment]
Dear riccardo-aiese,

I'm afraid not. In order to avoid some configuration issues, we fixed the
directory for STAR. We will consider updating it in the next release. By
the way, you can align the reads by STAR by yourself and run COMPSRA for
the annotation part separately. You can take bam/sam file to COMPSRA as
input when you running the annotation model.

Best Wishes,
  Jiang Li

**Comment by riccardo-aiese** [comment]
Dear Jiang Li,
thank you very much for your feedback and for this nice tool! I was able to run COMPSRA with my previously made genome index by creating a softlink from my index directory to the COMPRSA "bundle_v1/db/star/" folder. Maybe this solution can be useful for other users as well.

Kind regards
Riccardo

**Comment by cougarlj** [comment]
Dear riccardo-aiese,

Awesome, thanks! Your feedback is much appreciated. Thank you for using
COMPSRA in your research.

Best Wishes,
  Jiang Li
