### ISSUE TITLE
QC Module returns 0 FitReads

### ISSUE THREAD

**Issue by genericname2** [cougarlj/COMPSRA#42]
Hey,

I have just started working with COMPSRA for small RNA seq analysis and I see great potential in this program. Thanks a lot for sharing!

Having successfully installed COMPSRA and STAR according to your README, I now face the problem that all (!) trimmed files are sorted into the LowQualityRead file without respect to their PHRED score. This problem occurs both with my own data and the provided sample files. 

This is the command I use: 

COMPSRA user$ java -jar COMPSRA.jar -ref hg38 -qc -ra TGGAATTCTCGGGTGCCAAGG -rh 20 -rt 20 -rr 20 -in $HOME/Documents/Test/sample01.fastq -out $HOME/Documents/Test/example_out

Please find the QC report attached. As you can see, the removal of low quality reads, heads and tails works well, but later all reads are included in the LowQualityRead file. Do I miss anything obvious?

I work on a Apple M1Pro Chip (OSX Monterey), in case that is relevant. 

Thanks so much!

[example_out_QCReport.txt](https://github.com/cougarlj/COMPSRA/files/8987537/example_out_QCReport.txt)

**Comment by cougarlj** [comment]
Dear genericaname2,

Thank you for using COMPSRA in your study. We encourage to run COMPSRA in Linux, because we didn't test too much in MacOS. However, we will do more tests in MacOS in the next release. 

According to the QCReport, COMPSRA put all reads in the low quality files, this may be a potential bug for the parameter "-rlh". To solve this problem, would you like to add the parameter "-rlh 16" in the command and run COMPSRA again?

Best wishes,
  Jiang Li

**Comment by genericname2** [comment]
Dear Jiang Li,

Awesome, you were right. It seems like the .jar requires the option -rlh to work properly on my machine. I tried various n of -rlh n and all work. Thanks so much for this prompt reply.

Take care and good luck with COMPSRA2!
