### ISSUE TITLE
-mbi flag to index genome without input files?

### ISSUE THREAD

**Issue by pseudacriscrucifer** [cougarlj/COMPSRA#55]
Hi @cougarlj

Can I index my genome with -mbi without providing any input files?

I have tried `$ java -jar COMPSRA.jar -t 56 -ref mm10 -mt star -mbi ` (intentionally omitting -in and -out flags) after installing reference genome mm10 via COMPSRA with `$ java -jar COMPSRA.jar -tk -dr -ck star_mm10`, but am told there is an input error "Input Error! No file is set".

I only see in the manual that `-mbi` is needed to index but only the first time. Can you clarify the specific needs of this parameter? Can I not just index the genome with COMPSRA's STAR independent of input samples, like STAR does with `--runMode genomeGenerate`? As I understand the flag is needed with at least the first run, and then your indexed genome is set.

Just curious as I am planning ahead for new samples, and want to have everything square before receiving them.

Thanks!

**Comment by cougarlj** [comment]
Dear Users，

You should provide a fastq file when using "-mbi", because the input is
compulsory. You can put any fastq file or even written by you, because
building a genome index will be run first. In fact, COMPSRA does use STAR
to build the genome. You can run STAR by yourself, but you should put these
index files in the right directory. My suggestion is that you can put a
fastq file as input and run COMPSRA. When COMPSRA call STAR to build the
genome, it will show the command on the screen. Then you can stop COMPSRA
and run that command separately.

Best Wishes,
  Jiang Li
